# Setup
title:               Guides
tagline:             'Web'
description:         'Guides'
url:
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Luis Fernando García Acosta
  url:               https://twitter.com/lfgarcia98
  email:             lfgarciauaz@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
